#!/bin/sh

case "$1" in
    start)
        /usr/bin/module_load faulty
        modprobe hello
        ;;
    stop)
        /usr/bin/module_unload
        rmmod hello
        ;;
      *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac